(function(){
 const card=document.getElementById('btc-card');if(!card)return;
 const esc=window.HubLog.esc,money=v=>Number.isFinite(v)?'$'+v.toLocaleString('en-US',{maximumFractionDigits:1}):'—';
 const label=s=>({LONG:'ロング候補',SHORT:'ショート候補',WAIT:'見送り'}[s]||s);
 function draw(canvas,rows){const w=canvas.width=900,h=canvas.height=260,ctx=canvas.getContext('2d');if(!ctx||!rows.length)return;const low=Math.min(...rows.map(x=>x.l)),high=Math.max(...rows.map(x=>x.h)),span=high-low||1,y=v=>230-(v-low)/span*210;ctx.strokeStyle='#24303a';for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(0,20+i*50);ctx.lineTo(w,20+i*50);ctx.stroke();}rows.forEach((v,i)=>{const x=10+i*(w-30)/rows.length;ctx.strokeStyle=ctx.fillStyle=v.c>=v.o?'#71f4c8':'#fa7799';ctx.beginPath();ctx.moveTo(x,y(v.h));ctx.lineTo(x,y(v.l));ctx.stroke();ctx.fillRect(x-2,Math.min(y(v.o),y(v.c)),4,Math.max(1,Math.abs(y(v.o)-y(v.c))));});[['ema20','#ffc169'],['ema50','#87a6ff']].forEach(([key,color])=>{ctx.strokeStyle=color;ctx.beginPath();rows.forEach((v,i)=>{const x=10+i*(w-30)/rows.length;i?ctx.lineTo(x,y(v[key])):ctx.moveTo(x,y(v[key]));});ctx.stroke();});}
 function heat(canvas,book){const ctx=canvas.getContext('2d');canvas.width=900;canvas.height=230;const snapshots=book.snapshots||[];if(!ctx||!snapshots.length)return;const levels=snapshots.flatMap(x=>x.bids.concat(x.asks)),min=Math.min(...levels.map(x=>x.price)),max=Math.max(...levels.map(x=>x.price)),peak=Math.max(...levels.map(x=>x.volume))||1;ctx.fillStyle='#0b111a';ctx.fillRect(0,0,900,230);snapshots.forEach((s,i)=>s.bids.concat(s.asks).forEach(l=>{ctx.fillStyle='rgba(119,245,204,'+Math.max(.03,l.volume/peak)+')';ctx.fillRect(i*900/snapshots.length,210-(l.price-min)/(max-min||1)*200,900/snapshots.length,3);}));ctx.fillStyle='#b9ced3';ctx.font='13px sans-serif';ctx.fillText(money(max),6,14);ctx.fillText(money(min),6,225);}
 function render(j){
 if(j.status!=='ok')throw new Error(j.error||'データ未取得');const stale=Date.now()-j.generatedAt>30*60000,p=j.plan,f=j.frames,valid=!stale&&(!p.expiresAt||Date.now()<p.expiresAt),side=valid?p.side:'WAIT';
 card.innerHTML='<div class="btc-head"><div><span class="btc-kicker">BTC / MARKET WATCH</span><h2>ビットコイン司令室</h2></div><button id="btc-refresh">↻ 更新</button></div><p class="btc-sub">'+esc(j.source)+' · '+esc(new Date(j.generatedAt).toLocaleString('ja-JP'))+'<br>15分ごとに確認・定期実行は遅れる場合があります</p><div class="btc-price">'+money(f['5m'].price)+' <span class="btc-badge">'+esc(stale?'更新遅延／通知停止':label(side))+'</span></div><div class="btc-grid"><div class="btc-tile"><small>参考エントリー / 損切り</small><b>'+money(valid?p.entry:null)+'</b><p>SL '+money(valid?p.stop:null)+'</p></div><div class="btc-tile"><small>利確目安（価格変動前の参考値）</small><b>'+money(valid?p.targets[0]:null)+'</b><p>TP2 '+money(valid?p.targets[1]:null)+'</p></div><div class="btc-tile"><small>条件一致数（勝率ではありません）</small><b>'+p.matches+' / '+p.total+'</b><p>板 '+esc(j.confirmation.reason)+'</p></div></div><canvas id="btc-chart" aria-label="5分足とEMA20・EMA50"></canvas><p class="btc-sub">5分確定足 / オレンジ EMA20・青 EMA50</p><table><thead><tr><th>時間足</th><th>EMA配列</th><th>MACD</th><th>20MA乖離</th></tr></thead><tbody>'+Object.entries(f).map(([tf,a])=>'<tr><td>'+esc(tf)+'</td><td class="'+(a.trend==='UP'?'btc-up':'btc-down')+'">'+esc({UP:'上昇',DOWN:'下降',RANGE:'混在'}[a.trend])+'</td><td>'+esc(a.cross||(a.hist>0?'買い側':'売り側'))+(a.near?'・接近':'')+'</td><td>'+((a.price/a.ma20-1)*100).toFixed(2)+'%</td></tr>').join('')+'</tbody></table><div class="btc-tile"><small>板ヒートマップ / Binance Futures</small>'+(j.book.status==='ok'?'<canvas id="btc-heat" aria-label="直近20分の注文量ヒートマップ"></canvas><p class="btc-sub">清算予測とは別です。板取得 '+esc(new Date(j.book.at).toLocaleTimeString('ja-JP'))+'</p>':'<p>'+esc(j.book.reason||'板未確認')+'</p>')+'</div><ul>'+p.reasons.map(r=>'<li>'+esc(r)+'</li>').join('')+'</ul><p class="btc-sub">1時間ATRチャネル '+money(f['1H'].channel.lower)+' ～ '+money(f['1H'].channel.upper)+'<br>フラクタルは右側2本の確定後に判定。清算予測・独自インジケーター・SMCの完全再現は含みません。<br>板取得 '+j.quota.used+' / '+j.quota.limit+'ウェイト（直近24時間の安全上限）。板で補強された候補のみntfy通知。自動売買はしません。</p>';
 document.getElementById('btc-refresh').onclick=load;draw(document.getElementById('btc-chart'),f['5m'].chart);const c=document.getElementById('btc-heat');if(c)heat(c,j.book);
 }
 async function load(){try{render(await HubLog.loadBTC());}catch(e){card.innerHTML='<span class="btc-kicker">BTC / MARKET WATCH</span><h2>ビットコイン司令室</h2><p class="btc-sub">'+esc(e.message)+'<br>データが確認できるまで見送り。監視の初回実行・合い鍵の設定を確認してください。</p><button id="btc-retry">再読み込み</button>';document.getElementById('btc-retry').onclick=load;}}
 load();setInterval(load,300000);
})();
